minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash ./scripts/bump.sh
targets:
  - name: github
  - name: cocoapods
    specPath: BuzzSentry.podspec
  - name: registry
    sdks:
      cocoapods:sentry-cocoa:
